import { ReactNode } from 'react';
import type { Metadata } from 'next';
import 'kku-ui/lib/styles/index.css';
import '../style/globals.css';
import LayoutContainer from '@/layout/LayoutContainer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <LayoutContainer>{children}</LayoutContainer>
      </body>
    </html>
  );
}
